/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cachoahorasi;

/**
 *
 * @author Sammy Guergachi <sguergachi at gmail.com>
 */
public class JuegoD3 extends javax.swing.JFrame {

    /**
     * Creates new form JuegoD3
     */
    public JuegoD3() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPuntaje1 = new javax.swing.JLabel();
        jPuntajeEs = new javax.swing.JLabel();
        jPuntaje4 = new javax.swing.JLabel();
        jBjugar1 = new javax.swing.JButton();
        jBjugar2 = new javax.swing.JButton();
        jBjugar3 = new javax.swing.JButton();
        jBresultado = new javax.swing.JButton();
        jBexit = new javax.swing.JButton();
        jPuntaje2 = new javax.swing.JLabel();
        jPuntajePoker = new javax.swing.JLabel();
        jPuntaje5 = new javax.swing.JLabel();
        jPuntaje3 = new javax.swing.JLabel();
        jPuntajeFull = new javax.swing.JLabel();
        jPuntaje6 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jPuntaje11 = new javax.swing.JLabel();
        jPuntajeEs2 = new javax.swing.JLabel();
        jPuntaje44 = new javax.swing.JLabel();
        jPuntaje22 = new javax.swing.JLabel();
        jPuntajePoker2 = new javax.swing.JLabel();
        jPuntaje55 = new javax.swing.JLabel();
        jPuntaje33 = new javax.swing.JLabel();
        jPuntajeFull2 = new javax.swing.JLabel();
        jPuntaje66 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jPuntajeEs3 = new javax.swing.JLabel();
        jPuntaje444 = new javax.swing.JLabel();
        jPuntaje111 = new javax.swing.JLabel();
        jPuntajePoker3 = new javax.swing.JLabel();
        jPuntaje555 = new javax.swing.JLabel();
        jPuntaje222 = new javax.swing.JLabel();
        jPuntaje333 = new javax.swing.JLabel();
        jPuntajeFull3 = new javax.swing.JLabel();
        jPuntaje666 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Jugador_1");

        jLabel2.setText("Jugador_2");

        jLabel3.setText("Jugador_3");

        jPuntaje1.setText("0");

        jPuntajeEs.setText("0");

        jPuntaje4.setText("0");

        jBjugar1.setText("Juega1");
        jBjugar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBjugar1ActionPerformed(evt);
            }
        });

        jBjugar2.setText("Juega2");
        jBjugar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBjugar2ActionPerformed(evt);
            }
        });

        jBjugar3.setText("Juega3");
        jBjugar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBjugar3ActionPerformed(evt);
            }
        });

        jBresultado.setText("Resultado");
        jBresultado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBresultadoActionPerformed(evt);
            }
        });

        jBexit.setText("Salir");
        jBexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBexitActionPerformed(evt);
            }
        });

        jPuntaje2.setText("0");

        jPuntajePoker.setText("0");

        jPuntaje5.setText("0");

        jPuntaje3.setText("0");

        jPuntajeFull.setText("0");

        jPuntaje6.setText("0");

        jLabel13.setText("0");

        jLabel14.setText("0");

        jPuntaje11.setText("0");

        jPuntajeEs2.setText("0");

        jPuntaje44.setText("0");

        jPuntaje22.setText("0");

        jPuntajePoker2.setText("0");

        jPuntaje55.setText("0");

        jPuntaje33.setText("0");

        jPuntajeFull2.setText("0");

        jPuntaje66.setText("0");

        jLabel24.setText("0");

        jLabel25.setText("0");

        jPuntajeEs3.setText("0");

        jPuntaje444.setText("0");

        jPuntaje111.setText("0");

        jPuntajePoker3.setText("0");

        jPuntaje555.setText("0");

        jPuntaje222.setText("0");

        jPuntaje333.setText("0");

        jPuntajeFull3.setText("0");

        jPuntaje666.setText("0");

        jLabel35.setText("0");

        jLabel36.setText("0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jBresultado)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBexit)
                        .addGap(29, 29, 29))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jPuntaje3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jPuntaje1, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                                    .addComponent(jPuntaje2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jPuntajeFull, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jPuntajeEs, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                                    .addComponent(jPuntajePoker, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(14, 14, 14)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jPuntaje4, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                                    .addComponent(jPuntaje5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jPuntaje6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(60, 60, 60)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jPuntaje11, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                                    .addComponent(jPuntaje22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jPuntaje33, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jPuntajeEs2, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                                    .addComponent(jPuntajePoker2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jPuntajeFull2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jPuntaje44, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                                    .addComponent(jPuntaje55, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jPuntaje66, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(66, 66, 66)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jPuntaje222, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jPuntaje111, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jPuntaje333, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jPuntajeEs3, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                                    .addComponent(jPuntajePoker3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jPuntajeFull3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 21, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jBjugar1)
                                .addGap(140, 140, 140)
                                .addComponent(jBjugar2)
                                .addGap(162, 162, 162)
                                .addComponent(jBjugar3)
                                .addGap(8, 8, 8)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPuntaje444, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPuntaje555, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPuntaje666, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(116, 116, 116)
                        .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel35, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel36, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(jLabel1)
                .addGap(157, 157, 157)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(60, 60, 60))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBjugar1)
                    .addComponent(jBjugar2)
                    .addComponent(jBjugar3))
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jPuntaje1)
                    .addComponent(jPuntajeEs)
                    .addComponent(jPuntaje4)
                    .addComponent(jPuntaje11)
                    .addComponent(jPuntajeEs2)
                    .addComponent(jPuntaje44)
                    .addComponent(jPuntajeEs3)
                    .addComponent(jPuntaje444)
                    .addComponent(jPuntaje111))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jPuntaje2)
                    .addComponent(jPuntajePoker)
                    .addComponent(jPuntaje5)
                    .addComponent(jPuntaje22)
                    .addComponent(jPuntajePoker2)
                    .addComponent(jPuntaje55)
                    .addComponent(jPuntajePoker3)
                    .addComponent(jPuntaje555)
                    .addComponent(jPuntaje222))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jPuntaje3)
                    .addComponent(jPuntajeFull)
                    .addComponent(jPuntaje6)
                    .addComponent(jPuntaje33)
                    .addComponent(jPuntajeFull2)
                    .addComponent(jPuntaje66)
                    .addComponent(jPuntaje333)
                    .addComponent(jPuntajeFull3, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPuntaje666, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14)
                    .addComponent(jLabel24)
                    .addComponent(jLabel25)
                    .addComponent(jLabel35)
                    .addComponent(jLabel36))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBresultado)
                    .addComponent(jBexit))
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBjugar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBjugar1ActionPerformed
        
    }//GEN-LAST:event_jBjugar1ActionPerformed

    private void jBjugar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBjugar3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBjugar3ActionPerformed

    private void jBjugar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBjugar2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBjugar2ActionPerformed

    private void jBresultadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBresultadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBresultadoActionPerformed

    private void jBexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBexitActionPerformed
        MainUser game = new MainUser();
        game.setVisible(true);
        dispose();
    }//GEN-LAST:event_jBexitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JuegoD3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JuegoD3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JuegoD3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JuegoD3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JuegoD3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBexit;
    private javax.swing.JButton jBjugar1;
    private javax.swing.JButton jBjugar2;
    private javax.swing.JButton jBjugar3;
    private javax.swing.JButton jBresultado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jPuntaje1;
    private javax.swing.JLabel jPuntaje11;
    private javax.swing.JLabel jPuntaje111;
    private javax.swing.JLabel jPuntaje2;
    private javax.swing.JLabel jPuntaje22;
    private javax.swing.JLabel jPuntaje222;
    private javax.swing.JLabel jPuntaje3;
    private javax.swing.JLabel jPuntaje33;
    private javax.swing.JLabel jPuntaje333;
    private javax.swing.JLabel jPuntaje4;
    private javax.swing.JLabel jPuntaje44;
    private javax.swing.JLabel jPuntaje444;
    private javax.swing.JLabel jPuntaje5;
    private javax.swing.JLabel jPuntaje55;
    private javax.swing.JLabel jPuntaje555;
    private javax.swing.JLabel jPuntaje6;
    private javax.swing.JLabel jPuntaje66;
    private javax.swing.JLabel jPuntaje666;
    private javax.swing.JLabel jPuntajeEs;
    private javax.swing.JLabel jPuntajeEs2;
    private javax.swing.JLabel jPuntajeEs3;
    private javax.swing.JLabel jPuntajeFull;
    private javax.swing.JLabel jPuntajeFull2;
    private javax.swing.JLabel jPuntajeFull3;
    private javax.swing.JLabel jPuntajePoker;
    private javax.swing.JLabel jPuntajePoker2;
    private javax.swing.JLabel jPuntajePoker3;
    // End of variables declaration//GEN-END:variables
}
