/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cachoahorasi;

import javax.swing.JOptionPane;

/**
 *
 * @author Pabloneitor
 */
public class juega1vs1 extends javax.swing.JFrame {

    static int turnP;
    int  turno = 0;
    /**
     * Creates new form juega1vs1
     */
    public juega1vs1() {
        initComponents();
         jBjugar1.setEnabled(true);
        jBjugar2.setEnabled(false);
        
        /*if(turno % 2 == 0){
            
            JOptionPane.showMessageDialog(this,"turno jugardo 1");
            
        }
        if(turno % 2 != 0){
            jBjugar2.setEnabled(true);
            
            JOptionPane.showMessageDialog(this,"turno jugardo 2");
            
        }*/
    }
public static void turnP(int turno){
        turno = 0;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPuntaje1 = new javax.swing.JLabel();
        jPuntajeEs = new javax.swing.JLabel();
        jPuntaje4 = new javax.swing.JLabel();
        jPuntaje2 = new javax.swing.JLabel();
        jPuntajePoker = new javax.swing.JLabel();
        jPuntaje5 = new javax.swing.JLabel();
        jPuntaje3 = new javax.swing.JLabel();
        jPuntajeFull = new javax.swing.JLabel();
        jPuntaje6 = new javax.swing.JLabel();
        jPuntajeG1 = new javax.swing.JLabel();
        jPuntajeG2 = new javax.swing.JLabel();
        jBjugar1 = new javax.swing.JButton();
        jBresultado = new javax.swing.JButton();
        jPuntaje11 = new javax.swing.JLabel();
        jPuntajeES2 = new javax.swing.JLabel();
        jPuntaje44 = new javax.swing.JLabel();
        jPuntaje22 = new javax.swing.JLabel();
        jPuntajePoker2 = new javax.swing.JLabel();
        jPuntaje55 = new javax.swing.JLabel();
        jPuntaje33 = new javax.swing.JLabel();
        jPuntajeFull2 = new javax.swing.JLabel();
        jPuntaje66 = new javax.swing.JLabel();
        jPuntajeG12 = new javax.swing.JLabel();
        jPuntajeG22 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jBjugar2 = new javax.swing.JButton();
        jBexit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPuntaje1.setText("0");

        jPuntajeEs.setText("0");

        jPuntaje4.setText("0");

        jPuntaje2.setText("0");

        jPuntajePoker.setText("0");

        jPuntaje5.setText("0");

        jPuntaje3.setText("0");

        jPuntajeFull.setText("0");

        jPuntaje6.setText("0");

        jPuntajeG1.setText("0");

        jPuntajeG2.setText("0");

        jBjugar1.setText("Juega1");
        jBjugar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBjugar1ActionPerformed(evt);
            }
        });

        jBresultado.setText("Resultado");
        jBresultado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBresultadoActionPerformed(evt);
            }
        });

        jPuntaje11.setText("0");

        jPuntajeES2.setText("0");

        jPuntaje44.setText("0");

        jPuntaje22.setText("0");

        jPuntajePoker2.setText("0");

        jPuntaje55.setText("0");

        jPuntaje33.setText("0");

        jPuntajeFull2.setText("0");

        jPuntaje66.setText("0");

        jPuntajeG12.setText("0");

        jPuntajeG22.setText("0");

        jLabel1.setText("jugador_1");

        jLabel2.setText("jugador_2");

        jBjugar2.setText("Juega2");
        jBjugar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBjugar2ActionPerformed(evt);
            }
        });

        jBexit.setText("Salir");
        jBexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBexitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jPuntaje3, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                                            .addComponent(jPuntaje2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jPuntaje1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(21, 21, 21)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(jPuntajeFull, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                                                .addComponent(jPuntajeEs, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addComponent(jPuntajePoker, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(jBjugar1))
                                .addGap(21, 21, 21)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jPuntaje6, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                                    .addComponent(jPuntaje5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jPuntaje4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(150, 150, 150)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(jBjugar2))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jPuntaje22, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jPuntaje11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                                            .addComponent(jPuntaje33, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jPuntajeFull2, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                                            .addComponent(jPuntajeES2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jPuntajePoker2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jPuntaje66, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                                    .addComponent(jPuntaje55, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jPuntaje44, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(51, 51, 51))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jPuntajeG1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPuntajeG2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 214, Short.MAX_VALUE)
                        .addComponent(jPuntajeG12, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jBexit))
                            .addComponent(jPuntajeG22, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(49, 49, 49))))
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jBresultado)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBjugar1)
                    .addComponent(jBjugar2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jPuntaje1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPuntajeEs))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jPuntaje4, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPuntaje11)
                            .addComponent(jPuntaje44)))
                    .addComponent(jPuntajeES2, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jPuntaje2)
                        .addComponent(jPuntajePoker)
                        .addComponent(jPuntaje5, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jPuntaje22)
                        .addComponent(jPuntajePoker2)
                        .addComponent(jPuntaje55)))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jPuntaje3)
                    .addComponent(jPuntajeFull)
                    .addComponent(jPuntaje6)
                    .addComponent(jPuntaje33)
                    .addComponent(jPuntajeFull2)
                    .addComponent(jPuntaje66))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jPuntajeG2)
                        .addComponent(jPuntajeG22))
                    .addComponent(jPuntajeG1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPuntajeG12, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBresultado)
                    .addComponent(jBexit))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBjugar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBjugar1ActionPerformed
        
        DadosGen juega1 = new DadosGen();
        juega1.setVisible(true);
        turno++;
        System.out.println(turno);
        jBjugar1.setEnabled(false);
        jBjugar2.setEnabled(true);
        
    }//GEN-LAST:event_jBjugar1ActionPerformed

    private void jBresultadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBresultadoActionPerformed
        
        int p1 = 0;
        int p2 = 0;
        
        int num1 = Integer.parseInt( jPuntaje1.getText());
        int num2 = Integer.parseInt( jPuntaje2.getText());
        int num3 = Integer.parseInt( jPuntaje3.getText());
        int num4 = Integer.parseInt( jPuntaje4.getText());
        int num5 = Integer.parseInt( jPuntaje5.getText());
        int num6 = Integer.parseInt( jPuntaje6.getText());
        
        int num11 = Integer.parseInt( jPuntaje11.getText());
        int num22 = Integer.parseInt( jPuntaje22.getText());
        int num33 = Integer.parseInt( jPuntaje33.getText());
        int num44 = Integer.parseInt( jPuntaje44.getText());
        int num55 = Integer.parseInt( jPuntaje55.getText());
        int num66 = Integer.parseInt( jPuntaje66.getText());
        
        p1 = num1 + num2 + num3 + num4 + num5 + num6;
        p2 = num11 + num22 + num33 + num44 + num55 + num66;
        
        System.out.println(p1);
        System.out.println(p2);
        
        if(p1>p2){
            JOptionPane.showMessageDialog(this,
                "Puntaje Jugador 1:" + p1 + 
                "\nPuntaje Jugador 2:" + p2+
                "\n\nJugador 1 Gano");
        }else if(p2>p1){
            JOptionPane.showMessageDialog(this,
                "Puntaje Jugador 1:" + p1 + 
                "\nPuntaje Jugador 2:" + p2+
                "\n\nJugador 2 Gano");
        }else if(p1== p2){
            JOptionPane.showMessageDialog(this,
                "Puntaje Jugador 1:" + p1 + 
                "\nPuntaje Jugador 2:" + p2+
                "\n\nEmpate");
        }
        
    }//GEN-LAST:event_jBresultadoActionPerformed

    private void jBjugar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBjugar2ActionPerformed
    
        DadosGen juega1 = new DadosGen();
        juega1.setVisible(true);
        turno++;
        System.out.println(turno);
        jBjugar2.setEnabled(false);
         jBjugar1.setEnabled(true);
         
    }//GEN-LAST:event_jBjugar2ActionPerformed

    private void jBexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBexitActionPerformed
        MainUser game = new MainUser();
        game.setVisible(true);
        dispose();
    }//GEN-LAST:event_jBexitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(juega1vs1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(juega1vs1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(juega1vs1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(juega1vs1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new juega1vs1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBexit;
    public static javax.swing.JButton jBjugar1;
    public static javax.swing.JButton jBjugar2;
    private javax.swing.JButton jBresultado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    public static javax.swing.JLabel jPuntaje1;
    public static javax.swing.JLabel jPuntaje11;
    public static javax.swing.JLabel jPuntaje2;
    public static javax.swing.JLabel jPuntaje22;
    public static javax.swing.JLabel jPuntaje3;
    public static javax.swing.JLabel jPuntaje33;
    public static javax.swing.JLabel jPuntaje4;
    public static javax.swing.JLabel jPuntaje44;
    public static javax.swing.JLabel jPuntaje5;
    public static javax.swing.JLabel jPuntaje55;
    public static javax.swing.JLabel jPuntaje6;
    public static javax.swing.JLabel jPuntaje66;
    public static javax.swing.JLabel jPuntajeES2;
    public static javax.swing.JLabel jPuntajeEs;
    public static javax.swing.JLabel jPuntajeFull;
    public static javax.swing.JLabel jPuntajeFull2;
    public static javax.swing.JLabel jPuntajeG1;
    public static javax.swing.JLabel jPuntajeG12;
    public static javax.swing.JLabel jPuntajeG2;
    public static javax.swing.JLabel jPuntajeG22;
    public static javax.swing.JLabel jPuntajePoker;
    public static javax.swing.JLabel jPuntajePoker2;
    // End of variables declaration//GEN-END:variables
}
