/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cachoahorasi;

import static cachoahorasi.juega1vs1.jBjugar2;
import java.awt.Component;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author pabloneitor
 */
public class puntajeT extends javax.swing.JFrame {
       
    /**
     * Creates new form puntajeT
     */
    public puntajeT() {
        initComponents();
        buttonGroup1.add(jRadioButton1);
        buttonGroup1.add(jRadioButton2);
        buttonGroup1.add(jRadioButton3);
        buttonGroup1.add(jRadioButton4);
        buttonGroup1.add(jRadioButton5);
        buttonGroup1.add(jRadioButton6);
        buttonGroup1.add(jRadioButton7);
        buttonGroup1.add(jRadioButton8);
        buttonGroup1.add(jRadioButton9);
        buttonGroup1.add(jRadioButton10);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        jRadioButton6 = new javax.swing.JRadioButton();
        jRadioButton7 = new javax.swing.JRadioButton();
        jButtonSave = new javax.swing.JButton();
        jRadioButton8 = new javax.swing.JRadioButton();
        jRadioButton9 = new javax.swing.JRadioButton();
        jRadioButton10 = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jRadioButton1.setText("Puntaje Balas:");

        jRadioButton2.setText("Puntaje Tontos:");

        jRadioButton3.setText("Puntaje Trenes:");

        jRadioButton4.setText("Puntaje Cuadras:");

        jRadioButton5.setText("Puntaje Quinas:");

        jRadioButton6.setText("Puntaje Senas:");

        jRadioButton7.setText("Puntaje Grande:");

        jButtonSave.setText("Guardar");
        jButtonSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaveActionPerformed(evt);
            }
        });

        jRadioButton8.setText("Puntaje Escalera:");

        jRadioButton9.setText("Puntaje Poker:");

        jRadioButton10.setText("Puntaje Full:");

        jLabel1.setText("jLabel1");

        jLabel2.setText("jLabel2");

        jLabel3.setText("jLabel3");

        jLabel4.setText("jLabel4");

        jLabel5.setText("jLabel5");

        jLabel6.setText("jLabel6");

        jLabel7.setText("jLabel7");

        jLabel8.setText("jLabel8");

        jLabel9.setText("jLabel9");

        jLabel10.setText("jLabel10");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addComponent(jButtonSave)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jRadioButton10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel9))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jRadioButton7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel10))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jRadioButton6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel6))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jRadioButton5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jRadioButton2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jRadioButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jRadioButton3)
                                    .addComponent(jRadioButton4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3))))
                        .addContainerGap(103, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jRadioButton8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel7))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jRadioButton9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel8)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton1)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton2)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton3)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton4)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jRadioButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jRadioButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton8)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton9)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jRadioButton10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jRadioButton7)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)))
                .addGap(18, 18, 18)
                .addComponent(jButtonSave)
                .addGap(17, 17, 17))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
        //boton Guardar
    private void jButtonSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveActionPerformed
        
        if(juega1vs1.turnP <= 12){
            if(jRadioButton1.isSelected()){
            
                if(juega1vs1.turnP %2 == 0){
                    System.out.println(jLabel1.getText());

                    String nombre1;
                    nombre1 = jLabel1.getText();
                    juega1vs1.jPuntaje1.setText(nombre1);
                    
                    dispose();
                    
                }else if(juega1vs1.turnP %2 != 0) {
                    System.out.println(jLabel1.getText());

                    String nombre1;
                    nombre1 = jLabel1.getText();
                    juega1vs1.jPuntaje11.setText(nombre1);
                    
                    dispose();
                }
                juega1vs1.turnP++;
                System.out.println("turno:" + juega1vs1.turnP);
            }
            if(jRadioButton2.isSelected()){
               
                if(juega1vs1.turnP % 2 == 0){
                    System.out.println(jLabel2.getText());

                    String nombre2;
                    nombre2 = jLabel2.getText();
                    juega1vs1.jPuntaje2.setText(nombre2);
                    
                    dispose();
                    
                }else if(juega1vs1.turnP %2 != 0) {
                    System.out.println(jLabel2.getText());

                    String nombre2;
                    nombre2 = jLabel2.getText();
                    juega1vs1.jPuntaje22.setText(nombre2);
                    
                    dispose();
                }
                juega1vs1.turnP++;
                System.out.println("turno:" + juega1vs1.turnP);
            }
            if(jRadioButton3.isSelected()){
               
                if(juega1vs1.turnP % 2 == 0){
                    System.out.println(jLabel3.getText());

                    String nombre3;
                    nombre3 = jLabel3.getText();
                    juega1vs1.jPuntaje3.setText(nombre3);
                    
                    dispose();
                    
                }else if(juega1vs1.turnP %2 != 0) {
                    System.out.println(jLabel3.getText());

                    String nombre3;
                    nombre3 = jLabel3.getText();
                    juega1vs1.jPuntaje33.setText(nombre3);
                    
                    dispose();
                }
                juega1vs1.turnP++;
                System.out.println("turno:" + juega1vs1.turnP);
            }
            if(jRadioButton4.isSelected()){
                
                if(juega1vs1.turnP % 2 == 0){
                    System.out.println(jLabel4.getText());

                    String nombre4;
                    nombre4 = jLabel4.getText();
                    juega1vs1.jPuntaje4.setText(nombre4);
                    
                    dispose();
                    
                }else if(juega1vs1.turnP %2 != 0) {
                    System.out.println(jLabel4.getText());

                    String nombre4;
                    nombre4 = jLabel4.getText();
                    juega1vs1.jPuntaje44.setText(nombre4);
                    
                    dispose();
                }
                juega1vs1.turnP++;
                System.out.println("turno:" + juega1vs1.turnP);
            }
            if(jRadioButton5.isSelected()){
                
                if(juega1vs1.turnP % 2 == 0){
                    System.out.println(jLabel5.getText());

                    String nombre5;
                    nombre5 = jLabel5.getText();
                    juega1vs1.jPuntaje5.setText(nombre5);
                    
                    dispose();
                    
                }else if(juega1vs1.turnP %2 != 0) {
                    System.out.println(jLabel5.getText());

                    String nombre5;
                    nombre5 = jLabel5.getText();
                    juega1vs1.jPuntaje55.setText(nombre5);
                    
                    dispose();
                }
                juega1vs1.turnP++;
                System.out.println("turno:" + juega1vs1.turnP);
            }
            if(jRadioButton6.isSelected()){
                
                if(juega1vs1.turnP % 2 == 0){
                    System.out.println(jLabel6.getText());

                    String nombre6;
                    nombre6 = jLabel6.getText();
                    juega1vs1.jPuntaje6.setText(nombre6);
                    
                    dispose();
                    
                }else if(juega1vs1.turnP %2 != 0) {
                    System.out.println(jLabel6.getText());

                    String nombre6;
                    nombre6 = jLabel6.getText();
                    juega1vs1.jPuntaje66.setText(nombre6);
                    
                    dispose();
                }
                juega1vs1.turnP++;
                System.out.println("turno:" + juega1vs1.turnP);
            }
            if(jRadioButton8.isSelected()){
                
                if(juega1vs1.turnP % 2 == 0){
                    System.out.println(jLabel7.getText());

                    String nombre7;
                    nombre7 = jLabel7.getText();
                    juega1vs1.jPuntajeEs.setText(nombre7);
                    
                    dispose();
                    
                }else if(juega1vs1.turnP %2 != 0) {
                    System.out.println(jLabel7.getText());

                    String nombre7;
                    nombre7 = jLabel7.getText();
                    juega1vs1.jPuntajeES2.setText(nombre7);
                    
                    dispose();
                }
                juega1vs1.turnP++;
                System.out.println("turno:" + juega1vs1.turnP);
            }
            if(jRadioButton9.isSelected()){
                
                if(juega1vs1.turnP % 2 == 0){
                    System.out.println(jLabel8.getText());

                    String nombre8;
                    nombre8 = jLabel8.getText();
                    juega1vs1.jPuntajeFull.setText(nombre8);
                    
                    dispose();
                    
                }else if(juega1vs1.turnP %2 != 0) {
                    System.out.println(jLabel8.getText());

                    String nombre8;
                    nombre8 = jLabel8.getText();
                    juega1vs1.jPuntajeFull2.setText(nombre8);
                    
                    dispose();
                }
                juega1vs1.turnP++;
                System.out.println("turno:" + juega1vs1.turnP);
            }
            if(jRadioButton10.isSelected()){
                
                if(juega1vs1.turnP % 2 == 0){
                    System.out.println(jLabel9.getText());

                    String nombre9;
                    nombre9 = jLabel9.getText();
                    juega1vs1.jPuntajePoker.setText(nombre9);
                    
                    dispose();
                    
                }else if(juega1vs1.turnP %2 != 0) {
                    System.out.println(jLabel9.getText());

                    String nombre9;
                    nombre9 = jLabel9.getText();
                    juega1vs1.jPuntajePoker2.setText(nombre9);
                    
                    dispose();
                }
                juega1vs1.turnP++;
                System.out.println("turno:" + juega1vs1.turnP);
            }
        }
        
        
    }//GEN-LAST:event_jButtonSaveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(puntajeT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(puntajeT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(puntajeT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(puntajeT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new puntajeT().setVisible(true);
            }
        });
    
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    public static javax.swing.JButton jButtonSave;
    public static javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    public static javax.swing.JLabel jLabel2;
    public static javax.swing.JLabel jLabel3;
    public static javax.swing.JLabel jLabel4;
    public static javax.swing.JLabel jLabel5;
    public static javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton10;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JRadioButton jRadioButton7;
    private javax.swing.JRadioButton jRadioButton8;
    private javax.swing.JRadioButton jRadioButton9;
    // End of variables declaration//GEN-END:variables
}
