/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cachoahorasi;

/**
 *
 * @author pabloneitor
 */
public class DadosGen extends javax.swing.JFrame {
    private int obj;
    Cubilete objDado1 = new Cubilete();
    int [] dado = objDado1.cubileteLanza();       
    
    /**
     * Creates new form DadosGen
     */
    public DadosGen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPrimerT = new javax.swing.JButton();
        jSegundoT = new javax.swing.JButton();
        jVoltearD = new javax.swing.JButton();
        jTerminarT = new javax.swing.JButton();
        jSalir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jCheckDado1 = new javax.swing.JCheckBox();
        jCheckDado2 = new javax.swing.JCheckBox();
        jCheckDado3 = new javax.swing.JCheckBox();
        jCheckDado4 = new javax.swing.JCheckBox();
        jCheckDado5 = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPrimerT.setText("PrimerT");
        jPrimerT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPrimerTActionPerformed(evt);
            }
        });

        jSegundoT.setText("SegundoT");
        jSegundoT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSegundoTActionPerformed(evt);
            }
        });

        jVoltearD.setText("VoltearD");
        jVoltearD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jVoltearDActionPerformed(evt);
            }
        });

        jTerminarT.setText("TerminarT");
        jTerminarT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTerminarTActionPerformed(evt);
            }
        });

        jSalir.setText("Salir");
        jSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSalirActionPerformed(evt);
            }
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("0");

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("0");

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("0");

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("0");

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("0");

        jCheckDado1.setText("jCheckBox1");
        jCheckDado1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/dados-01.gif"))); // NOI18N
        jCheckDado1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckDado1ActionPerformed(evt);
            }
        });

        jCheckDado2.setText("jCheckBox2");
        jCheckDado2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/dados-02.gif"))); // NOI18N
        jCheckDado2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckDado2ActionPerformed(evt);
            }
        });

        jCheckDado3.setText("jCheckBox3");
        jCheckDado3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/dados-03.gif"))); // NOI18N
        jCheckDado3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckDado3ActionPerformed(evt);
            }
        });

        jCheckDado4.setText("jCheckBox4");
        jCheckDado4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/dados-04.gif"))); // NOI18N
        jCheckDado4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckDado4ActionPerformed(evt);
            }
        });

        jCheckDado5.setText("jCheckBox5");
        jCheckDado5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/dados-05.gif"))); // NOI18N
        jCheckDado5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckDado5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jTerminarT))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPrimerT)
                            .addComponent(jSegundoT)
                            .addComponent(jVoltearD))))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jCheckDado1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jCheckDado2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jCheckDado3, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSalir)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jCheckDado4, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jCheckDado5, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(68, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPrimerT)
                        .addGap(28, 28, 28)
                        .addComponent(jSegundoT)
                        .addGap(26, 26, 26)
                        .addComponent(jVoltearD)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTerminarT)
                            .addComponent(jSalir))
                        .addGap(33, 33, 33))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jCheckDado1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCheckDado2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCheckDado3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckDado5, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCheckDado4, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(48, 132, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

   //Primer Tiro       
    private void jPrimerTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPrimerTActionPerformed
        //dado1
        jLabel1.setText(""+dado[0]);
        imagenesResult objImag1 = new imagenesResult();
        jCheckDado1.setIcon(objImag1.Imaen(dado[0]));
        //dado2
        jLabel2.setText(""+dado[1]);
        imagenesResult objImag2 = new imagenesResult();
        jCheckDado2.setIcon(objImag2.Imaen(dado[1]));
        //dado3
        jLabel3.setText(""+dado[2]);
        imagenesResult objImag3 = new imagenesResult();
        jCheckDado3.setIcon(objImag3.Imaen(dado[2]));
        //dado4
        jLabel4.setText(""+dado[3]);
        imagenesResult objImag4 = new imagenesResult();
        jCheckDado4.setIcon(objImag4.Imaen(dado[3]));
        //dado5
        jLabel5.setText(""+dado[4]);
        imagenesResult objImag5 = new imagenesResult();
        jCheckDado5.setIcon(objImag5.Imaen(dado[4]));
        
        jPrimerT.setEnabled(false);
    }//GEN-LAST:event_jPrimerTActionPerformed
    //Segundo Tiro
    private void jSegundoTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSegundoTActionPerformed
        //Dado_1
        if(jCheckDado1.isSelected()){
            dado[0] = objDado1.lanzarDado();
            jLabel1.setText(""+dado[0]);
            imagenesResult objImag1 = new imagenesResult();
            jCheckDado1.setIcon(objImag1.Imaen(dado[0]));
        }
        //Dado_2
        if(jCheckDado2.isSelected()){
            dado[1] = objDado1.lanzarDado();
            jLabel2.setText(""+dado[1]);
            imagenesResult objImag2 = new imagenesResult();
            jCheckDado2.setIcon(objImag2.Imaen(dado[1]));
        }
        //Dado_3
        if(jCheckDado3.isSelected()){
            dado[2] = objDado1.lanzarDado();
            jLabel3.setText(""+dado[2]);
            imagenesResult objImag3 = new imagenesResult();
            jCheckDado3.setIcon(objImag3.Imaen(dado[2]));
        }
        //Dado_4
        if(jCheckDado4.isSelected()){
            dado[3] = objDado1.lanzarDado();
            jLabel4.setText(""+dado[3]);
            imagenesResult objImag4 = new imagenesResult();
            jCheckDado4.setIcon(objImag4.Imaen(dado[3]));
        }
        //Dado_5
        if(jCheckDado5.isSelected()){
            dado[4] = objDado1.lanzarDado();
            jLabel5.setText(""+dado[4]);
            imagenesResult objImag5 = new imagenesResult();
            jCheckDado5.setIcon(objImag5.Imaen(dado[4]));
        }
        
        jCheckDado1.setSelected(false);
        jCheckDado2.setSelected(false);
        jCheckDado3.setSelected(false);
        jCheckDado4.setSelected(false);
        jCheckDado5.setSelected(false);
        
        jSegundoT.setEnabled(false);
    }//GEN-LAST:event_jSegundoTActionPerformed
    //Voltear Dado(s)
    private void jVoltearDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jVoltearDActionPerformed
       
           //Dado_1
            if(jCheckDado1.isSelected()){
                dado[0] = objDado1.voltearDado(dado[0]);
                jLabel1.setText(""+dado[0]);
                imagenesResult objImag1 = new imagenesResult();
                jCheckDado1.setIcon(objImag1.Imaen(dado[0]));
                
            }
            //Dado_2
            if(jCheckDado2.isSelected()){
                dado[1] = objDado1.voltearDado(dado[1]);
                jLabel2.setText(""+dado[1]);
                imagenesResult objImag2 = new imagenesResult();
                jCheckDado2.setIcon(objImag2.Imaen(dado[1]));
                
            }
            //Dado_3
            if(jCheckDado3.isSelected()){
                dado[2] = objDado1.voltearDado(dado[2]);
                jLabel3.setText(""+dado[2]);
                imagenesResult objImag3 = new imagenesResult();
                jCheckDado3.setIcon(objImag3.Imaen(dado[2]));
               
            }
            //Dado_4
            if(jCheckDado4.isSelected()){
                dado[3] = objDado1.voltearDado(dado[3]);
                jLabel4.setText(""+dado[3]);
                imagenesResult objImag4 = new imagenesResult();
                jCheckDado4.setIcon(objImag4.Imaen(dado[3]));
                
            }
            //Dado_5
            if(jCheckDado5.isSelected()){
                dado[4] = objDado1.voltearDado(dado[4]);
                jLabel5.setText(""+dado[4]);
                imagenesResult objImag5 = new imagenesResult();
                jCheckDado5.setIcon(objImag5.Imaen(dado[4]));
            }
        
        
    }//GEN-LAST:event_jVoltearDActionPerformed
    //Terminar Turno
    private void jTerminarTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTerminarTActionPerformed
        int b = 0; 
        int t = 0;
        int tr = 0;
        int c = 0;
        int q = 0;
        int se = 0;
        for(int i = 0;i < dado.length;i++){
            if(dado[i] == 1){
                b = b + dado[i];
            }else if(dado[i] == 2){
                t = t + dado[i];
            }else if(dado[i] == 3){
                tr = tr + dado[i];
            }else if(dado[i] == 4){
                c = c + dado[i];
            }else if(dado[i] == 5){
                q = q + dado[i];
            }else if(dado[i]==6){
                se = se + dado[i];
            }
        }
        System.out.println("puntaje de balas: "+ b);
         System.out.println("puntaje de tontos: "+ t);
          System.out.println("puntaje de trenes: "+ tr);
           System.out.println("puntaje de cuadras: "+ c);
            System.out.println("puntaje de quinas: "+ q);
             System.out.println("puntaje de senas: "+ se);
             
    }//GEN-LAST:event_jTerminarTActionPerformed
    //Salida de Juego
    private void jSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSalirActionPerformed
        dispose();
    }//GEN-LAST:event_jSalirActionPerformed

    private void jCheckDado1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckDado1ActionPerformed
        if(jCheckDado1.isSelected()){
            imagenes1 objImag1 = new imagenes1();
            jCheckDado1.setIcon(objImag1.gifDado1(dado[0]));
        }
    }//GEN-LAST:event_jCheckDado1ActionPerformed

    private void jCheckDado2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckDado2ActionPerformed
        if(jCheckDado2.isSelected()){
            imagenes1 objImag1 = new imagenes1();
            jCheckDado2.setIcon(objImag1.gifDado1(dado[1]));
        }
    }//GEN-LAST:event_jCheckDado2ActionPerformed

    private void jCheckDado3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckDado3ActionPerformed
        if(jCheckDado3.isSelected()){
            imagenes1 objImag1 = new imagenes1();
            jCheckDado3.setIcon(objImag1.gifDado1(dado[2]));
        }
    }//GEN-LAST:event_jCheckDado3ActionPerformed

    private void jCheckDado4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckDado4ActionPerformed
        if(jCheckDado4.isSelected()){
            imagenes1 objImag1 = new imagenes1();
            jCheckDado4.setIcon(objImag1.gifDado1(dado[3]));
        }
    }//GEN-LAST:event_jCheckDado4ActionPerformed

    private void jCheckDado5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckDado5ActionPerformed
        if(jCheckDado5.isSelected()){
            imagenes1 objImag1 = new imagenes1();
            jCheckDado5.setIcon(objImag1.gifDado1(dado[4]));
        }
    }//GEN-LAST:event_jCheckDado5ActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DadosGen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DadosGen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DadosGen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DadosGen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DadosGen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox jCheckDado1;
    private javax.swing.JCheckBox jCheckDado2;
    private javax.swing.JCheckBox jCheckDado3;
    private javax.swing.JCheckBox jCheckDado4;
    private javax.swing.JCheckBox jCheckDado5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JButton jPrimerT;
    private javax.swing.JButton jSalir;
    private javax.swing.JButton jSegundoT;
    private javax.swing.JButton jTerminarT;
    private javax.swing.JButton jVoltearD;
    // End of variables declaration//GEN-END:variables
}
